// List all movies
GET http://localhost:3000/movies
###

// List a single movie by ID
GET http://localhost:3000/movies/2
###

// Update a single movie by ID
PUT http://localhost:3000/movies/2
Content-Type: application/json

{
    "year": 1950,
    "title": "esse é o video 010",
    "studios": "meus estudios",
    "producers": "os produtores",
    "winner": "no"
}
###

// Delete a single movie by ID
DELETE http://localhost:3000/movies/2
###

// List producers by custom algorithm
GET http://localhost:3000/producers