POST http://localhost:3000/upload-movies
Accept: application/json
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/plain

< ./test.csv
year;title;studios;producers;winner
1980;Can't Stop the Music;Associated Film Distribution;Allan Carr;yes
1980;Cruising;Lorimar Productions, United Artists;Jerry Weintraub;
--MfnBoundry--
###
GET http://localhost:3000/movies
###
GET http://localhost:3000/movies/2
###
PUT http://localhost:3000/movies/2
Content-Type: application/json

{
    "year": 1950,
    "title": "esse é o video 010",
    "studios": "meus estudios",
    "producers": "os produtores",
    "winner": "no"
}
###
DELETE http://localhost:3000/movies/2
###
GET http://localhost:3000/producers